name: SonarQube Scan

on:
  push:
    branches:
      - master  # Or the default branch you're using
  pull_request:
    branches:
      - '*/*'  # Or the branch you're using for PRs

jobs:
  sonarQubeScan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          organization: Sangeetha M   # Replace with your SonarCloud organization name
          projectKey: sangeethamkrishnan2000-cpu                  # Replace with your SonarQube project key
          projectName: gees-workout-v1                # Replace with your SonarQube project name
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
